### ISSUE TITLE
Error: Unable to allocate 0 bytes for an array with shape

### ISSUE THREAD

**Issue by DenkingOfficial** [NVlabs/stylegan2-ada#105]
I'm trying to run training process on [biked](https://decode.mit.edu/projects/biked/) dataset with command:
`python train.py --outdir ./results --snap=10 --data=./datasets/biked --augpipe=bgcfnc --res=512`

But I'm getting this error:

`np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train.py", line 561, in <module>
    main()
  File "train.py", line 553, in main
    run_training(**vars(args))
  File "train.py", line 416, in run_training
    run_desc, training_options = setup_training_options(**hyperparam_options)
  File "train.py", line 105, in setup_training_options
    dataset_obj = dataset.load_dataset(**args.train_dataset_args) # try to load the data and see what comes out
  File "C:\Temporary Software\stylegan2-ada\training\dataset.py", line 231, in load_dataset
    mirror_augment=mirror_augment, repeat=repeat, shuffle=shuffle)
  File "C:\Temporary Software\stylegan2-ada\training\dataset.py", line 114, in __init__
    self._tf_labels_var = tflib.create_var_with_large_initial_value(self._np_labels, name='labels_var')
  File "C:\Temporary Software\stylegan2-ada\dnnlib\tflib\tfutil.py", line 234, in create_var_with_large_initial_value
    zeros = tf.zeros(initial_value.shape, initial_value.dtype)
  File "C:\Users\Andrew\anaconda3\envs\Stylegan\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1871, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "C:\Users\Andrew\anaconda3\envs\Stylegan\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1829, in _constant_if_small
    return constant(value, shape=shape, dtype=dtype, name=name)
  File "C:\Users\Andrew\anaconda3\envs\Stylegan\lib\site-packages\tensorflow\python\framework\constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "C:\Users\Andrew\anaconda3\envs\Stylegan\lib\site-packages\tensorflow\python\framework\constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\Andrew\anaconda3\envs\Stylegan\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 464, in make_tensor_proto
    nparray = np.empty(shape, dtype=np_dt)
numpy.core._exceptions.MemoryError: Unable to allocate 0 bytes for an array with shape (1073741824, 0) and data type float32`

Also I'm getting this error with every dataset that I'm trying to train
If someone need info about my environment I'll provide it

**Comment by DenkingOfficial** [comment]
There is my packages that I installed

absl-py==0.14.0
astor==0.8.1
cached-property==1.5.2
certifi==2021.5.30
chardet==3.0.4
gast==0.5.2
google-pasta==0.2.0
grpcio==1.41.0
h5py==2.9.0
idna==2.8
imageio==2.9.0
imageio-ffmpeg==0.4.2
importlib-metadata==4.8.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.3.4
numpy==1.21.2
Pillow==6.2.1
protobuf==3.18.0
requests==2.22.0
scipy==1.3.3
six==1.16.0
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
tqdm==4.49.0
typing-extensions==3.10.0.2
urllib3==1.25.11

**Comment by yyyzzzhao** [comment]
I encounter this error too. Have you solve it? Thank you.
