### ISSUE TITLE
dimension error when resuming model from stylegan2

### ISSUE THREAD

**Issue by QuinnFreedman** [NVlabs/stylegan2-ada#21]
I trained a model in stylegan2. When I try to `--resume` training with that model using stylegan2-ada, I get the following error:

```
Constructing networks...
Setting up TensorFlow plugin "fused_bias_act.cu": Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Loading... Done.
Resuming from "/datadrive/stylegan2_results/00003-stylegan2-wikiart-128-1gpu-config-f/network-snapshot-002286.pkl"
Traceback (most recent call last):
  File "train.py", line 561, in <module>
    main()
  File "train.py", line 553, in main
    run_training(**vars(args))
  File "train.py", line 451, in run_training
    training_loop.training_loop(**training_options)
  File "/datadrive/stylegan2-ada/training/training_loop.py", line 128, in training_loop
    G.copy_vars_from(rG)
  File "/datadrive/stylegan2-ada/dnnlib/tflib/network.py", line 511, in copy_vars_from
    self._components[name].copy_vars_from(src_comp)
  File "/datadrive/stylegan2-ada/dnnlib/tflib/network.py", line 508, in copy_vars_from
    self.copy_own_vars_from(src_net)
  File "/datadrive/stylegan2-ada/dnnlib/tflib/network.py", line 481, in copy_own_vars_from
    tfutil.set_vars({self._get_vars()[name]: value for name, value in value_dict.items() if name in self._get_vars()})
  File "/datadrive/stylegan2-ada/dnnlib/tflib/tfutil.py", line 227, in set_vars
    run(ops, feed_dict)
  File "/datadrive/stylegan2-ada/dnnlib/tflib/tfutil.py", line 33, in run
    return tf.get_default_session().run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (3, 3, 512, 512) for Tensor 'G_synthesis/64x64/Conv0_up/weight/new_value:0', which has shape '(3, 3, 512, 256)'
```

My original model was trained on a 128x128 dataset using the following command:

```
docker exec -ti -w /datadrive/stylegan2 wonderful_driscoll python run_training.py --num-gpus=1 --data-dir=/datadrive/data/sg2-datasets --dataset=wikiart-128 --total-kimg 10000 --config=config-f
```

I'm running stylegan2-ada with this command:
```
docker exec -ti -w /datadrive/stylegan2-ada wonderful_driscoll python train.py --outdir=/datadrive/stylegan2ada_results/ --gpus=1 --data=/datadrive/data/sg2-datasets/wikiart-128/ --resume /datadrive/stylegan2_results/00003-stylegan2-wikiart-128-1gpu-config-f/network-snapshot-002286.pkl --metrics fid50k 
```

Am I correct in understanding that sg2-ada is supposed to be backwards compatible with sg2 datasets? If so, am I supposed to be doing something different or is there a bug here? Thanks!

**Comment by QuinnFreedman** [comment]
My mistake! I seems like I forgot to add `--cfg=stylegan2` to the sg2-ada command. Things seem to be working now.
