### ISSUE TITLE
Dimension mismatch error (using gray-scale dataset)

### ISSUE THREAD

**Issue by mulkong** [NVlabs/stylegan2-ada#8]
I am now running the model on a gray-scale dataset. As a test, I try to run projector.py, but I get the following error.

`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 572, in set_shape
    unknown_shape)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 1 and 3. Shapes are [1,1,256,256] and [?,3,?,?].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "projector.py", line 288, in <module>
    main()
  File "projector.py", line 283, in main
    project(**vars(parser.parse_args()))
  File "projector.py", line 225, in project
    proj.set_network(Gs)
  File "projector.py", line 118, in set_network
    self._dist = self._lpips.get_output_for(proc_images_expr, self._target_images_var)
  File "/home/ubuntu/jyk_project/stylegan2-ada/dnnlib/tflib/network.py", line 371, in get_output_for
    out_expr = self._build_func(*final_inputs, **build_kwargs)
  File "<string>", line 140, in lpips_network
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 575, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 1 and 3. Shapes are [1,1,256,256] and [?,3,?,?].`

Please. help is appreciated.

Thank you.

**Comment by metemadi** [comment]
Hi - having the same trouble - did you ever come to a resolution?

I think the issue is here:
'https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/metrics/vgg16_zhang_perceptual.pkl'

This model I believe expects RGB inputs - having trouble doing the right surgery on the code to change it to grayscale (1 channel) inputs..
