### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by tempdeltavalue** [NVlabs/stylegan2-ada#82]
tf.contrib doesn't exist in 2.0.
https://github.com/tensorflow/tensorflow/issues/31350

AttributeError: module 'tensorflow' has no attribute 'get_variable'

**Comment by johndpope** [comment]
check my tf2 fork - https://github.com/johndpope/stylegan2-ada

more elaborate fork with a training fix 
https://github.com/johndpope/stylegan2-ada/commit/0345d1b71017dd081ae49dd956cc1a3366febf0a

**Comment by Louvivien** [comment]
Even with your repo I get this: 


```
Constructing networks...
Traceback (most recent call last):
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/train.py", line 614, in <module>
    main()
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/train.py", line 606, in main
    run_training(**vars(args))
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/train.py", line 495, in run_training
    training_loop.training_loop(**training_options)
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/training/training_loop.py", line 123, in training_loop
    Gs = G.clone('Gs')
         ^^^^^^^^^^^^^
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 463, in clone
    net.copy_vars_from(self)
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 496, in copy_vars_from
    src_net._get_vars()
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 298, in _get_vars
    self._vars = OrderedDict(self._get_own_vars())
                             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 287, in _get_own_vars
    self._init_graph()
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 152, in _init_graph
    out_expr = self._build_func(*self._input_templates, **build_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/training/networks.py", line 231, in G_main
    num_layers = components.synthesis.input_shape[1]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 233, in input_shape
    return self.input_shapes[0]
           ^^^^^^^^^^^^^^^^^
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 220, in input_shapes
    self._input_shapes = [t.shape.as_list() for t in self.input_templates]
                                                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 268, in input_templates
    self._init_graph()
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/dnnlib/tflib/network.py", line 152, in _init_graph
    out_expr = self._build_func(*self._input_templates, **build_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivien/Documents/letthemlive/StyleGAN2-ADA/stylegan2-ada/training/networks.py", line 388, in G_synthesis
    noise_inputs.append(tf.get_variable(f'noise{layer_idx}', shape=shape, initializer=tf.initializers.random_normal(), trainable=False))
                        ^^^^^^^^^^^^^^^
AttributeError: module 'tensorflow' has no attribute 'get_variable'
```

It says that the tf.get_variable function is not available in TensorFlow 2.x versions.
