### ISSUE TITLE
dataset_tool.py create_from_images PIL.UnidentifiedImageError on Colab

### ISSUE THREAD

**Issue by MoemaMike** [NVlabs/stylegan2-ada#87]
I have created 2 stylegan2-ada projects on Colab Pro in last week.  One with intended dataset 2500 1024x1024 images, the other with intended dataset of 8000 1024x1024. Both times dataset_tool.py/create_from_images ran for a long time but eventually faulted and stopped short of completing my dataset. both times for PIL.UnidentifiedImageError for files that really do exist and are valid imge files no different from all the others in my collection. All images are jpg generated by Lightroom. 

More urgently i would like to know how to work round this issue. This run below succesfully created 3000 of the target 8000  tfrecords. How do i most efficiently create the remainder? Can one run create_from_image incrementally or does it have to create all tfrecords in one single run? Any advice would be appreciated. 

```
!python stylegan2-ada/dataset_tool.py create_from_images drive/MyDrive/ganDatasets/carn-closeups drive/MyDrive/ganRawImages/carn-closeups

Loading images from "drive/MyDrive/ganRawImages/carn-closeups"
Creating dataset "drive/MyDrive/ganDatasets/carn-closeups"
stylegan2-ada/dataset_tool.py:96: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  'data': tf.train.Feature(bytes_list=tf.train.BytesList(value=[quant.tostring()]))}))
Added 3539 images.
Traceback (most recent call last):
  File "stylegan2-ada/dataset_tool.py", line 993, in <module>
    execute_cmdline(sys.argv)
  File "stylegan2-ada/dataset_tool.py", line 988, in execute_cmdline
    func(**vars(args))
  File "stylegan2-ada/dataset_tool.py", line 672, in create_from_images
    img = np.asarray(PIL.Image.open(image_filenames[order[idx]]))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'drive/MyDrive/ganRawImages/carn-closeups/_DSC6859.jpg'
```

**Comment by MoemaMike** [comment]
fwiw here is how i worked around the issue
1. the images that PIL fails on are valid images in every way that i can discern. They open fine in all image viewers and were created via Lightroom export just lke all the other images in the dataset. 
2. At each interrupted create_from_image i would have to replace the file that it failed on with a new file of the same name and rerun the entire  create_from_image process again until the next failure. It was not enough to just delete the file because at least on google drive it seems the name of the file was still present in directory listing even after trashing, some google drive latency i suspect
3. This happened for about 10 images out of 8000 but required 10 full reruns of create_from_image because AFAIK create_from_image is not re-entrant and therefore cannot be continued from where it was interrupted? it is either complete success or rerun from scratch? This can be very time consuming
4. Not sure if this codebase is going forward. if so a more robust error handling of the PIL failures would be greatly appreciated ... i.e catch error, log failed file, ski, and continue
